### ISSUE TITLE
Confusing before/after methods.

### ISSUE THREAD

**Issue by proofit404** [wemake-services/django-test-migrations#10]
These two methods do the same thing.

Why not call it `migrate` and reload the graph each time?

From my understanding `before(('app', '0003'))` should migrate to dependencies of `0003` but not the `0003` itself.

**Comment by sobolevn** [comment]
Hm 🤔

**Comment by wwarne** [comment]
I was confused too.
I thought that `before` are applying all migrations but the specified one. Because it says `generate a state before the actual migration happens`.
So if we have migrations 0001, 0002, 0003 then  I thought `before(('app', '003'))` would apply only 0001 and 0002 but actually it includes 0003.
Maybe we need the better clarification about it in documentation?

**Comment by sobolevn** [comment]
Yes, we must update confusing parts!

@wwarne do you want to help with a PR? What parts were the most confusing?

**Comment by wwarne** [comment]
@sobolevn Yes, I would love to. 

The most confusing was that in my mind `migrator.before(('main_app', '0004'))` had to create the state **before** the migration named 0004.  I was expecting the .before function to behave like a range function. And in reality migration 0004 is included and applied too. 

After failing my tests I read examples again and understood that I should use
`migrator.before(('main_app', '0003'))` (
some preparations
`migrator.after(('main_app', '0004'))`
some checks

I will try to come up with the suggestion about changing the documentation. Right now I'm not sure how to describe `before` and `action` methods short and  clearly.

**Comment by sobolevn** [comment]
Ok, today I got confused myself. Spent 20 minutes debugging `ArrayField` from `django`. But I have `after` / `before` misuse. 

I need to refactor it in the future versions.

**Comment by shaleh** [comment]
Perhaps `initial_migration` and `tested_migration`? The goal here is to set a state, do some prep work, and then test a migration.

**Comment by sobolevn** [comment]
I like this naming, @shaleh! 👍 

PRs are welcome!

**Comment by skarzi** [comment]
what do you think about: `apply_initial_migrations(targets)` and `apply_tested_migrations(targets)`?

**Comment by sobolevn** [comment]
Yes, I like this one more. Because it has a verb in it.
