### ISSUE TITLE
add possibility to run tests against all django supported DB engines 

### ISSUE THREAD

**Issue by skarzi** [wemake-services/django-test-migrations#107]
Our library is closely connected with databases, so it will be really nice to have tests that run on each database engine supported by Django (especially when #91 will be merged), so I'm opening this issue to open some discussion about adding other database engines to our CI

**Comment by sobolevn** [comment]
Great idea!

**Comment by skarzi** [comment]
After quick research I see 2 solutions:

+ custom `docker-compose.yml` file with definition of images with all DB engines
+ GitHub jobs services - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices - with definition of images with all DB engines

Then we can parametrize our testing app settings with some envs to use proper DB engine.

Do you think we should extend our test matrix with DB engines or just add single includes like we did with `django master`?

**Comment by sobolevn** [comment]
Single include is fine. Otherwise, we would end up with lots and lots of tests.
By the way, which method is easier in your opinion: `docker-compose` or github jobs?

**Comment by skarzi** [comment]
Personally I think docker-compose approach can be better, because it will be easier to quickly setup DBs locally, just `docker-compose up mysql-db` and tweaking some envs/settings values and we can run tests or investigate something using any DB engine
