### ISSUE TITLE
Extension 'ltree' already exists.

### ISSUE THREAD

**Issue by mrswats** [wemake-services/django-test-migrations#153]
I wrote a test for the migration I am writing by hand, followed the guide for unittest and so on.  Now, when I run pytest to run the actual test (this one alone) I get into the followin error:

```
E               django.db.utils.ProgrammingError: extension "ltree" already exists
```

I searched here as best as I could but could not find anything. 

Worth mentioning we run our tests with pytest and we are using the `pytest-django` plugin to manage django setup and so on.

Thank you in advance for your help!

**Comment by mrswats** [comment]
I will be happy to submit a PR if I can figure out how :)

**Comment by sobolevn** [comment]
Looks like for some reason you have `ltree` extension setup twice.
We don't deal with this (or any other) extensions in this package directly. 

I would recommend to check what exactly the state of the database before the test run and what does it actually run.

Does this help you? 🙂

**Comment by mrswats** [comment]
Yes, I was just investigating this issue and I noticed the initial migration had this line:
```
schema_editor.execute("CREATE EXTENSION ltree;")
```
So I can definitely change this to `CREATE IF NOT EXIST`.

However, what I do not understand is why would this migration run twice for the same database. I guess that at init time the extension creates two databases (or something similar) under the hood to be able to get the old_state and the new_state ?

In any case, making this change seems that it solved the issue, now I am running into other issues, but I think that's on me :)

Let me not close this issue for now so I can investigate this further and leave a good response in this thread as documentation.

**Comment by sobolevn** [comment]
Do you use `pytest` for regular tests and `unittest` for this one?

**Comment by mrswats** [comment]
No, I use pytest as a runner with unittest cases (the DRF unittest anyway, but unittest none the less).

**Comment by mrswats** [comment]
But yes, that was it.

The problem stemmed from that first migration that was trying to create the extension twice and by adding the adequate SQL line in the migration that ads the extension fixed it. 

Thank you for your help!
