### ISSUE TITLE
Add this project to "django packages"

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/django-test-migrations#2]

**Comment by sobolevn** [comment]
@asfaltboy @blueyed I have used pieces of your code in this project.
And gave you a credit for it: https://github.com/wemake-services/django-test-migrations#credits

Thanks a lot! Without it it would be 100% harder.

I would like to hear your feedback if any.

**Comment by fernandogrd** [comment]
Cool, glad it helped you!
