### ISSUE TITLE
typing_extensions is still required in newer Python versions

### ISSUE THREAD

**Issue by jkugler** [wemake-services/django-test-migrations#288]
This line is in poetry.lock
```
[package.dependencies]
attrs = ">=20"
typing_extensions = {version = "*", markers = "python_version >= \"3.7\" and python_version < \"3.8\""}
```
However, on a fresh Ubuntu 20.04 system, after I install pytest and pytest-django, I got this error when I ran my tests:
```
traceback snipped
  File "/home/vagrant/.local/share/virtualenvs/redacted-ikMrF094/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/home/vagrant/.local/share/virtualenvs/redacted/lib/python3.8/site-packages/django_test_migrations/contrib/pytest_plugin.py", line 6, in <module>
    from django_test_migrations.constants import MIGRATION_TEST_MARKER
  File "/home/vagrant/.local/share/virtualenvs/redacted/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/home/vagrant/.local/share/virtualenvs/redacted/lib/python3.8/site-packages/django_test_migrations/constants.py", line 1, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'
```
It would appear this module still needs to depend on typing_extensions.

Ubuntu 20.04

Python 3.8.6

**Comment by skarzi** [comment]
Hello :wave: 

I have called the following commands on Python 3.8.6 with auto generated `pyproject.toml`:

1. `poetry add --dev pytest`
2. `poetry add --dev pytest-django`
3. `poetry add --dev django-test-migrations`

And everything seems to work like expected - `django-test-migration==1.2.0` and `typing_extension==4.2.0` are installed.

Could you please check what version of `django-test-migration` is installed in your case?

**Comment by jkugler** [comment]
In my virtual env, I have django_test_migrations-1.2.0

**Comment by skarzi** [comment]
Could you please post the simplest/minimal `pyproject.toml` and `poetry.lock` files that cause this error?

**Comment by jkugler** [comment]
I can't seem to reproduce it now. I am wondering if I was relying on a project's out-of-date Pipefile.lock. I'll let you know if I come across this again.

**Comment by sobolevn** [comment]
Thanks! 👍
