### ISSUE TITLE
Checks failing on MariaDB

### ISSUE THREAD

**Issue by kytta** [wemake-services/django-test-migrations#321]
In 5.7, MySQL renamed `MAX_STATEMENT_TIME` to be `MAX_EXECUTION_TIME`. [MariaDB kept the old name](https://mariadb.com/kb/en/system-variable-differences-between-mariadb-101-and-mysql-57/). Due to this, when using MariaDB as database, checks fail with the following:
```
django.db.utils.OperationalError: (1193, "Unknown system variable 'MAX_EXECUTION_TIME'")
```

Is there a way that we could detect MariaDB and use a different name? 🤔 Django doesn't differentiate between MySQL and MariaDB, sadly

**Comment by sobolevn** [comment]
I think we can: based on some exact sql query, like this: https://database.guide/6-ways-to-check-your-mariadb-version/
