### ISSUE TITLE
other `django-test-migrations`

### ISSUE THREAD

**Issue by skarzi** [wemake-services/django-test-migrations#37]
Hello :wave: 
last year I have encountered problems with Django’s migrations similar to these described by you on your [blog](https://sobolevn.me/2019/10/testing-django-migrations) and after that, I also have decided to create a library to test that kind of code properly - http://github.com/skarzi/django-test-migrations.
We were both inspired by the same articles/code snippets so our code is almost identical.

I wanted to release my code after some polishing and refactoring, but you did it first. I think we could start working together on one project t's always more profitable for the community. Below I list some issues me and other developers (it has been used in several side and commercial projects) have spotted in my implementation:

+ multiple DB support - in your implementation it's possible but requires creating few instances of migrator
+ properly run initial migrations - currently, it runs all migrations forward (it's done either by Django’s test case or pytest's `--migrations` cli option) and then migrations are reverted to these specified in `.before()`. Such an approach can cause a really ugly tracebacks.
+ properly clean DB after tests - currently `migrate` command is called but it's run only on `default` DB (check Django’s test case  source code for proper solution - https://github.com/django/django/blob/master/django/test/testcases.py#L1015)
+ detection and update of `settings.MIGRATION_MODULES` for migration tests

I also wanted to add intergration with [`factory_boy`](https://github.com/FactoryBoy/factory_boy) - creating models' instances manually (with `ModelClass.objects.create()` or `ModelClass.objects.bulk_create()`) is really tiresome, but I need to do more experiments to decide on the best API for that.

**Comment by sobolevn** [comment]
Hi, @skarzi! Thanks a lot for your feedback. Awesome that we like the similar solutions to the common problems 😄 

I have sent you a maintainer invite. I really enjoy working with you, and I hope that community can benefit from that as well! I think that we can start by creating tasks for each individual point of your list. And make this project mature enough. 

I personally thought about adding `factory_boy` (or even `hypothesis`) to generate data before the actual migration. This can be really helpful.

**Comment by skarzi** [comment]
Thank you for an invitation ;)
I will add these issues today or tomorrow evening
