### ISSUE TITLE
Optional check that ensure statement timeout is set on supported databases

### ISSUE THREAD

**Issue by skarzi** [wemake-services/django-test-migrations#47]
See https://github.com/wemake-services/wemake-django-template/issues/1064 for more details.

**Comment by skarzi** [comment]
I've investigated this issue more deeply, so generally only 2 backends support setting to stop queries that execution take too long: 

+ `postgresql` via [`statement_timeout`](https://www.postgresql.org/docs/current/runtime-config-client.html)
+ `mysql` via [`max_execution_time`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_execution_time)

When working on this feature we can think about adding some more checks for other database settings, because to implement this check we can reuse common components:

+ new database backend's related class (something similar to [`django.db.backends.base.features`](https://github.com/django/django/blob/master/django/db/backends/base/features.py)) for getting settings names and values for particular thing (e.g timing out statements)
+ some common validators of this settings (e.g. `statement_timeout` cannot be turned off or set to too big value)

so adding new checks should be relatively simple.

**Comment by sobolevn** [comment]
Thanks a lot for your thoughtful research! 

I guess we can start with `postgres` / `mysql` and someday eventually come to more complex engines.
