### ISSUE TITLE
integration with factory-boy or other similar solution

### ISSUE THREAD

**Issue by skarzi** [wemake-services/django-test-migrations#78]
Many of existing Django projects use [`factory-boy`](https://github.com/FactoryBoy/factory_boy) or other similar solution to create models instances before actual tests, so it will be really handy to provide some integration with such tools to make migrations testing easier and less verbose than `Model.objects.create()` etc.

**Comment by sobolevn** [comment]
Thanks a lot for the suggestion! However, I think that data creation is out of scope of this project.
Currently I don't have any problems creating it with a code like this:

```python
@pytest.mark.django_db
def test_my_app_migration0031(migrator, fakery):
    """Ensures that the some fields are deleted correctly."""
    old_state = migrator.before(
        ('my_app', '0030_pre'),
    )
    my_model = old_state.apps.get_model(
        'my_app', 'MyModel',
    )

    kwargs_to_delete = [
        {'a': None},
        {'b': 'in_progress'},
        {'c': None},
        {'d': ''},
        {'e': ''},
        {'f': None},
    ]

    for kwargs in kwargs_to_delete:
        fakery.m(my_model)(**kwargs)

    assert my_model.objects.count() == len(kwargs_to_delete)

    new_state = migrator.after(('bot_app', '0031_some'))
    my_model = new_state.apps.get_model(
        'my_app', 'MyModel',
    )

    assert not my_model.objects.count()
```

**Comment by skarzi** [comment]
What's exactly `fakery` fixtures?
Is it provided by some `pytest` plugin or it's implemented by you?

**Comment by sobolevn** [comment]
Oh, sorry. It is a tool similar to `factoryboy`: https://github.com/fcurella/django-fakery
I use it in all of my projects. It is just awesome!

**Comment by skarzi** [comment]
Looks really good! I will give it a shot, even just for migrations tests.
I will also do some deeper research on possible ways to integrate `factory-boy with our project.`

**Comment by antonagestam** [comment]
It seems like using factories would be pretty hard without either duplicating factories for each tested state, or getting a lot of strange errors because factories are always a mirror of the last database state. To me neither of those options seem worth it.

**Comment by skarzi** [comment]
That's true, it's possible, but implementation will be much more complicated than the benefits, so I am closing this issue

**Comment by sobolevn** [comment]
https://github.com/fcurella/django-fakery can be used, because it uses `_meta` to inspect models in runtime.
You don't have to pre-define anything. So, that's quite useful.
