### ISSUE TITLE
`migrator` fixture clashes with `db` fixture

### ISSUE THREAD

**Issue by lee-vg** [wemake-services/django-test-migrations#82]
I am preloading some test data via a migration, and once my sole migration test has run, it wipes that data out and other tests fail the next time i do a test run.

The culprit is 
```py
@pytest.fixture()
def migrator_factory(request, transactional_db, django_db_use_migrations):
```
If I remove `transactional_db` then tests pass again

My conftest looks like this:
```py
@pytest.fixture(autouse=True)
def enable_db_access_for_all_tests(db):
    pass


@pytest.fixture()
def migrator():
    migrator = Migrator(database='default')
    yield migrator
    migrator.reset()
```

My custom migrator fixture gets tests passing again.

**Comment by skarzi** [comment]
hello @lee-vg 

which version of `django-test-migrations` do you use?
Could you check if `django-test-migrations` installed from `master` branch still has this problem?

I think you have spotted problem described in #38 which is already solved on `master`

**Comment by lee-vg** [comment]
we were using 0.2.0 so we upgraded to 0.3.0, but we still had issues.
Telling. the migrator to not reset after each test did the trick as the tests already rollback after each test run.

```py
@pytest.fixture(autouse=True)
def enable_db_access_for_all_tests(db):
    pass


# Override django-test-migrations `migrator` fixture.
# https://github.com/wemake-services/django-test-migrations/issues/82
@pytest.fixture()
def migrator(request):
    migrator = Migrator(database='default')
    return migrator
```

**Comment by skarzi** [comment]
That's because test setup/teardown was fixed in #76 which is not released yet.

I would be really grateful for checking if your problem is still present with `django-test-migrations` installed from `master` branch

**Comment by lee-vg** [comment]
No. Firstly it complains that typing_extensions is not installed.
Then i get this error

```
tests/test_vFlow/test_migrations/test_saved_filing_period_migrations.py::test_filing_status_canceled_to_cancelled_rename_0083 - AttributeError: 'Migrator' object has no attribute 'before'
```

**Comment by skarzi** [comment]
In the meantime we have merged #83 which renamed `Migrator` methods:

+ `before` to `apply_initial_migration`
+ `after` to `apply_tested_migration`

**Comment by skarzi** [comment]
@lee-vg do you have any other struggles with `django-test-migrations`?
If everything works fine, I will close this issue

**Comment by skarzi** [comment]
I am closing this issue, if you have any other problems, please let us know
