### ISSUE TITLE
Migrate to tox.

### ISSUE THREAD

**Issue by proofit404** [wemake-services/django-test-migrations#9]

**Comment by skarzi** [comment]
Is this transition to `tox` still needed?
GitHub actions seems to work pretty well

**Comment by proofit404** [comment]
Reproduce different environments locally will be hard without tox.

**Comment by sobolevn** [comment]
I don't understand the necessity of reproducing environments locally at all.
I even don't have required python versions installed. I only have two: latest 3.7 and 2.7 (default on macos)

There's a CI for this kind of tasks. You push, it build in parallel: fast, convenient, simple. 

For some reason only python has this strange tooling. Node, rust (rustup has some similarities, but it is not importantn), haskell, elixir do not have them: and it is a good thing.
