### ISSUE TITLE
add possibility to run/skip only migrations tests

### ISSUE THREAD

**Issue by skarzi** [wemake-services/django-test-migrations#96]
Calling tests with via pytest with `--migrations` or via Django's standard test runner (which apply migrations by default when using `TransactionTestCase`) can slow down tests a bit and when running tests in CI/CD pipeline we want to get feedback as fast as possible and often it's good idea to run standard and fast unit tests in parallel with migrations tests etc.

Currently it's really hard to run/skip *only* migrations tests and the easy solution is to add:

+ `marker` to every node that requested `migrator_factory` fixture
+ `tag` to every subclass of `MigrationTestCase` - https://docs.djangoproject.com/en/3.0/topics/testing/tools/#tagging-tests

**Comment by roszczypalam** [comment]
Hello everyone ! I would like to help you guys in development of this excellent tool. 
I will catch it as first contribution if it's ok for you : - )

**Comment by skarzi** [comment]
Hi,

Sure, thanks a lot!
Let us know if you have any question
